apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"assignment1","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"assignment1"}},"template":{"metadata":{"labels":{"app":"assignment1"}},"spec":{"containers":[{"image":"jovanvelanac/assignment3:latest","name":"assignment1","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2020-05-11T17:24:25Z"
  generation: 1
  name: assignment1
  namespace: default
  resourceVersion: "110041"
  selfLink: /apis/apps/v1/namespaces/default/deployments/assignment1
  uid: 943a24bf-cdca-4089-a742-8ddadbe46bf0
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: assignment1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: assignment1
    spec:
      containers:
      - image: jovanvelanac/assignment3:latest
        imagePullPolicy: Always
        name: assignment1
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-05-11T17:24:25Z"
    lastUpdateTime: "2020-05-11T17:24:25Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-05-11T17:34:26Z"
    lastUpdateTime: "2020-05-11T17:34:26Z"
    message: ReplicaSet "assignment1-f57974594" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
