apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment1
  template:
    metadata:
      labels:
        app: assignment1
    spec:
      containers:
      - name: assignment1
        image: gethecked/go-dock
        ports:
        - containerPort: 8081
